version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godot
    - ireturn
    - mnd
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
    varnamelen:
      ignore-names:
        - err
        - ok
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/uzumaki-inc/stay_or_go)
        - default
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
