run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - gomnd # deprecated
    - godot # コメントにピリオド必須はいらない
    - execinquery # deprecated
    - forbidigo # CLIツールでfmt.Printが使えないと困るため
    - gochecknoinits # initメソッドを有効化する
    - depguard # cmdからimportできなくなるため
    - gochecknoglobals # globalな変数の利用を許可する(フラグで利用するため フラグで利用する変数はマジックコメントで退避してもいいかも
    - exportloopref # deprecated
    - ireturn # メソッドの返り値にinterfaceを返す必要があるため
    - gofumpt # wslのルールとバッティングするのでOff
    - exhaustruct # 構造体初期化時にすべて埋めるのは手間なので一時的にOff

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  varnamelen: # 変数の文字数
    ignore-names:
      - err
      - ok
issues:
  exclude-rules:
    # disable funlen for all _test.go files
    - path: _test.go
      linters:
        - funlen