# golangci-lint configuration file
# See: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - gomnd # deprecated
    - godot # コメントにピリオド必須はいらない
    - execinquery # deprecated
    - forbidigo # CLIツールでfmt.Printが使えないと困るため
    - gochecknoinits # initメソッドを有効化する
    - depguard # cmdからimportできなくなるため
    - gochecknoglobals # globalな変数の利用を許可する(フラグで利用するため)
    - exportloopref # deprecated
    - ireturn # メソッドの返り値にinterfaceを返す必要があるため
    # - gofumpt # wslのルールとバッティングするのでOff
    - exhaustruct # 構造体初期化時にすべて埋めるのは手間なので一時的にOff

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/uzumaki-inc/stay_or_go)
      - default
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  varnamelen: # 変数の文字数
    ignore-names:
      - err
      - ok

issues:
