source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.0.0'

gem "self_hosting", git: "https://github.com/konyu/self_hosting_gem.git", tag: "v1.0.0"

gem 'webmock', '~> 7.0.0', :require => false

